version: "3.9"
services:
  app:
    build: .
    ports:
    - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
    - .:/app
  db:
    image: "postgres"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=Flask_SQLAlchemy
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin123
    volumes:
    - ./data/db:/var/lib/postgresql/data
